version: '3.9'
services:
  cofeeapp:
    build: .
    working_dir: /var/www
    volumes:
      - ./:/var/www
      
    command: bash -c "npm install && npx prisma generate && npm run start:dev cofeeapp"
    env_file:
      - .env
    ports:
      - 3000:3000
    # depends_on:
    #   - mysqlcofeeapp

  # mysqlcofeeapp:
  #   image: mysql:latest
  #   container_name: mysqlcofeeapp
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: adriansyahganteng
  #     MYSQL_DATABASE: cofeeapp
  #     MYSQL_USER: cofeeapp
  #     MYSQL_PASSWORD: adriansyahganteng
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"